export const SHOW_MODAL_SIGN = "USER/SHOW_MODAL_SIGN";
export const HIDE_MODAL_SIGN = "USER/HIDE_MODAL_SIGN";
export const SHOW_MODAL_USERDATA = "USER/SHOW_MODAL_USERDATA";
export const HIDE_MODAL_USERDATA = "USER/HIDE_MODAL_USERDATA";
export const USER_EMAIL = "USER/USER_EMAIL";
export const GET_CONTACTS = "CONTACTS/GET_CONTACTS";
export const APP_LOGIN = "APP/APP_LOGIN";
export const APP_LOGOUT = "APP/APP_LOGOUT";
